### ISSUE TITLE
Unable to load app component

### ISSUE THREAD

**Issue by kenince** [mariodavid/cuba-example-using-wizard#1] opened 2018-08-09 09:40 UTC
Hello Mario,

Tried loading this project to sample it but I got the error on the attached. Can you assist?

![errorloadingcomponent](https://user-images.githubusercontent.com/37148271/43891164-57cbef04-9bd1-11e8-9f2d-bae16201706f.png)

Kind Regards,
E'm

**Comment by mariodavid** [comment] 2018-08-09 10:52
Hi,

Yes i can :) the problem is that the wizard component is not yet published as 0.1.0. The snapshot versions are not published to bintray also.

To solve the problem:

Git clone the app component repo:

https://github.com/mariodavid/cuba-component-wizard

Open in studio and install the app component (menu > build > install app component).

Then try again to open the example. This should work...

Bye

**Comment by kenince** [comment] 2018-08-29 14:33
Thank Mario,

I'm trying this out now. 

I have sent you an email on your official email (mario@die-davids.de) address for an engagement I am proposing.

Could you please get back if you can. 

My Skype ID is keninceem. 

Regards, 
Kenince

**Comment by mariodavid** [comment] 2019-02-03 05:53
Version 0.2.0 is already released and this app is update. Will close this for now. If you see any further questions, fell free to ask :)

**Closed as completed by mariodavid** 2019-02-03 05:53 UTC
